"""add_tag_table_replace_workspace_tags

Revision ID: ed84ca408aa0
Revises: 405fb75e0f68
Create Date: 2026-03-28 21:36:11.368058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ed84ca408aa0'
down_revision: Union[str, Sequence[str], None] = '405fb75e0f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'path', name='uq_tag_workspace_path')
    )
    op.create_index('idx_tags_path_gist', 'tags', ['path'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False)
    op.add_column('documents', sa.Column('tag_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_documents_tag'), table_name='documents')
    op.create_index(op.f('ix_documents_tag_id'), 'documents', ['tag_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'tag')
    op.drop_index(op.f('idx_workspaces_tags_gist'), table_name='workspaces', postgresql_using='gist')
    op.drop_column('workspaces', 'tags')
    op.drop_column('workspaces', 'tags_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('tags_embeddings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('tags', postgresql.ARRAY(sqlalchemy_utils.types.ltree.LtreeType()), server_default=sa.text("'{}'::ltree[]"), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_workspaces_tags_gist'), 'workspaces', ['tags'], unique=False, postgresql_using='gist')
    op.add_column('documents', sa.Column('tag', sqlalchemy_utils.types.ltree.LtreeType(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_tag_id'), table_name='documents')
    op.create_index(op.f('ix_documents_tag'), 'documents', ['tag'], unique=False)
    op.drop_column('documents', 'tag_id')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('idx_tags_path_gist', table_name='tags', postgresql_using='gist')
    op.drop_table('tags')
    # ### end Alembic commands ###
