"""add api key and origins to workspace table

Revision ID: fff91b71f19d
Revises: 35e545cc9e3c
Create Date: 2026-03-18 14:06:07.212674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import secrets

# revision identifiers, used by Alembic.
revision: str = 'fff91b71f19d'
down_revision: Union[str, Sequence[str], None] = '35e545cc9e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('workspaces', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('allowed_origins', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False))

    bind = op.get_bind()    
    result = bind.execute(sa.text("SELECT id FROM workspaces WHERE api_key IS NULL"))
    
    for row in result:
        workspace_id = row[0]
        new_key = f"pk_ws_{secrets.token_urlsafe(32)}"        
        bind.execute(
            sa.text("UPDATE workspaces SET api_key = :key WHERE id = :id"),
            {"key": new_key, "id": workspace_id}
        )

    op.alter_column('workspaces', 'api_key', nullable=False)
    op.create_index(op.f('ix_workspaces_api_key'), 'workspaces', ['api_key'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_api_key'), table_name='workspaces')
    op.drop_column('workspaces', 'allowed_origins')
    op.drop_column('workspaces', 'api_key')
    # ### end Alembic commands ###
