services:

  ########################################################################################
  ########################################################################################
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  ########################################################################################
  ########################################################################################
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --save 600 1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ########################################################################################
  ########################################################################################
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    command: server -s3 -dir=/data -ip.bind=0.0.0.0
    env_file: .env
    ports:
      - "9333:9333"   # Master UI
      - "9340:9340"   # Volume Server
      - "8888:8888"   # Filer UI
      - "8333:8333"   # S3 Endpoint
      - "7333:7333"   # WebDAV
      - "23646:23646" # Admin UI
    volumes:
      - seaweedfs_data:/data

  ########################################################################################
  ########################################################################################
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 10

  ########################################################################################
  ########################################################################################
  api:
    build:
      context: ./api
      target: api
    container_name: api
    command: python -m app.main
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./api:/code
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_healthy
      redis:
        condition: service_started

  ########################################################################################
  ########################################################################################
  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true 
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_started

  ########################################################################################
  ########################################################################################
  worker:
    build:
      context: ./api
      target: worker
    container_name: worker
    command: taskiq worker app.taskiq.main:broker # --reload --reload-dir app --log-level DEBUG
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONDONTWRITEBYTECODE=1
      - WATCHFILES_FORCE_POLLING=1 
    volumes:
      - ./api:/code
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  ########################################################################################
  ########################################################################################
  scheduler:
    build:
      context: ./api
      target: api
    container_name: scheduler
    command: taskiq scheduler app.taskiq.main:scheduler
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./api:/code
    depends_on:
      redis:
        condition: service_started

  ########################################################################################
  ########################################################################################
  # open-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: open-webui
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   env_file: .env
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #     - WEBUI_SECRET_KEY=33ca73fa4c671e23fc0939010993099e319ff0f3b0163af7e267846574eff39b
  #   volumes:
  #     - open_webui_data:/app/backend/data
  #   depends_on:
  #     ollama:
  #       condition: service_healthy

  ########################################################################################
  ########################################################################################
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  redis_insight_data:
  seaweedfs_data:
  # open_webui_data: